=== ErjieIsHeree/WsDataAccessExercises/02_EsquemaXML/ColeccionVideojuegos.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.example.org/ColeccionVideojuegos" xmlns:tns="http://www.example.org/ColeccionVideojuegos" elementFormDefault="qualified">

    <element name="ColeccionVideojuegos" type="tns:videojuegos"></element>

    <complexType name="videojuego">
    	<sequence>
    		<element name="desarrollador" type="string" maxOccurs="unbounded" minOccurs="1"></element>
    		<element name="plataforma" type="string" maxOccurs="unbounded" minOccurs="1"></element>
    		<element name="genero" type="string" maxOccurs="unbounded" minOccurs="0"></element>
    		<element name="anioLanzamiento" type="int" maxOccurs="1" minOccurs="1"></element>
    		<element name="PEGI" type="int" maxOccurs="1" minOccurs="1"></element>
    		<element name="copiasDisponibles" type="int" maxOccurs="1" minOccurs="1"></element>
    	</sequence>
    	<attribute name="titulo" type="string"></attribute>
    </complexType>

    <complexType name="videojuegos">
    	<sequence>
    		<element name="videojuego" type="tns:videojuego" maxOccurs="unbounded" minOccurs="0"></element>
    	</sequence>
    </complexType>
</schema>

=== ErjieIsHeree/WsDataAccessExercises/02_EsquemaXML/ColeccionVideojuegos.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:ColeccionVideojuegos xmlns:tns="http://www.example.org/ColeccionVideojuegos" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/ColeccionVideojuegos ColeccionVideojuegos.xsd ">
	<tns:videojuego titulo="Wu Kong">
		<tns:desarrollador>Erjie Xia</tns:desarrollador>
		<tns:plataforma>PC, PS5, XBOX SERIES X</tns:plataforma>
		<tns:anioLanzamiento>2024</tns:anioLanzamiento>
		<tns:PEGI>16</tns:PEGI>
		<tns:copiasDisponibles>1000000</tns:copiasDisponibles>
	</tns:videojuego>
	<tns:videojuego titulo="Among Us">
		<tns:desarrollador>Erjie Xia</tns:desarrollador>
		<tns:plataforma>Movil, PC</tns:plataforma>
		<tns:anioLanzamiento>2016</tns:anioLanzamiento>
		<tns:PEGI>12</tns:PEGI>
		<tns:copiasDisponibles>9999999</tns:copiasDisponibles>
	</tns:videojuego>
	<tns:videojuego titulo="Dress to Impress">
		<tns:desarrollador>Ana Gomez</tns:desarrollador>
		<tns:plataforma>PC, MOVIL, PS5, XBOX SERIES X</tns:plataforma>
		<tns:anioLanzamiento>2014</tns:anioLanzamiento>
		<tns:PEGI>9</tns:PEGI>
		<tns:copiasDisponibles>99999999</tns:copiasDisponibles>
	</tns:videojuego>
	<tns:videojuego titulo="Pou">
		<tns:desarrollador>Eduardo Franco</tns:desarrollador>
		<tns:plataforma>MOVIL</tns:plataforma>
		<tns:anioLanzamiento>2009</tns:anioLanzamiento>
		<tns:PEGI>4</tns:PEGI>
		<tns:copiasDisponibles>999999999</tns:copiasDisponibles>
	</tns:videojuego>
	<tns:videojuego titulo="Minecraft">
		<tns:desarrollador>Camila Sanchez</tns:desarrollador>
		<tns:plataforma>PC, PS5, XBOX SERIES, MOVIL</tns:plataforma>
		<tns:anioLanzamiento>2002</tns:anioLanzamiento>
		<tns:PEGI>12</tns:PEGI>
		<tns:copiasDisponibles>999999999</tns:copiasDisponibles>
	</tns:videojuego></tns:ColeccionVideojuegos>
